### ISSUE TITLE
Cannot compile on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by baykovr** [curl/trurl#67]
(Hello Daniel, thank you for the project)

I cloned trurl and fetched `libcurl4-openssl-dev` on Ubuntu Focal (20.04) and found that `libcurl4-openssl-dev` (7.68.0-1ubuntu2.18) alone is insufficient.

I see the note in the readme on CURLUPART_ZONEID, is it the case that the minimum required version for compiling is thus 7.81.0?

```
~/src/github.com/trurl (master ✔) make 
cc  -W -Wall -pedantic -g   -c -o trurl.o trurl.c
trurl.c: In function ‘get’:
trurl.c:365:18: error: ‘CURLUE_NO_ZONEID’ undeclared (first use in this function); did you mean ‘CURLUPART_ZONEID’?
  365 |             case CURLUE_NO_ZONEID:
      |                  ^~~~~~~~~~~~~~~~
      |                  CURLUPART_ZONEID
trurl.c:365:18: note: each undeclared identifier is reported only once for each function it appears in
trurl.c:369:55: warning: implicit declaration of function ‘curl_url_strerror’; did you mean ‘curl_multi_strerror’? [-Wimplicit-function-declaration]
  369 |               fprintf(stderr, PROGNAME ": %s (%s)\n", curl_url_strerror(rc),
      |                                                       ^~~~~~~~~~~~~~~~~
      |                                                       curl_multi_strerror
trurl.c:47:25: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
   47 | #define PROGNAME        "trurl"
      |                         ^~~~~~~
trurl.c:369:31: note: in expansion of macro ‘PROGNAME’
  369 |               fprintf(stderr, PROGNAME ": %s (%s)\n", curl_url_strerror(rc),
      |                               ^~~~~~~~
trurl.c:369:44: note: format string is defined here
  369 |               fprintf(stderr, PROGNAME ": %s (%s)\n", curl_url_strerror(rc),
      |                                           ~^
      |                                            |
      |                                            char *
      |                                           %d
make: *** [<builtin>: trurl.o] Error 1
```

**Comment by bagder** [comment]
This is mentioned in the README. We need to add some #ifdef magic to handle older libcurl versions proper.

**Comment by bagder** [comment]
I believe this is fixed now.
