### ISSUE TITLE
Fails to build with glibc-2.43

### ISSUE THREAD

**Issue by abbbi** [curl/trurl#431]
hi,

during an archive wide rebuild of all debian packages with glibc-4.3 it was noticed that trurl fails to build:

```
| cc -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/build/reproducible-path/trurl-0.16.1=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard $(curl-config --cflags) -W -Wall -Wshadow -pedantic  
-Wconversion -Wmissing-prototypes -Wwrite-strings -Wsign-compare -Wno-sign-conversion -Werror -g -Wdate-time -D_FORTIFY_SOURCE=2  -c -o trurl.o trurl.c                                                                                                                          
| ./scripts/cd2nroff trurl.md > trurl.1                                                                                                                                                                                                                                          
| trurl.c: In function ???encodeassign???:                                                                                                                                                                                                                                       
| trurl.c:488:13: error: initialization discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                   
|   488 |   char *p = strchr(query, '=');                                                                                                                                                                                                                                        
|       |             ^~~~~~                                                                                                                                                                                                                                                     
| trurl.c: In function ???getarg???:                                                                                                                                                                                                                                             
| trurl.c:605:20: error: initialization discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                   
|   605 |     char *equals = strchr(&flag[2], '=');                                                                                                                                                                                                                              
|       |                    ^~~~~~                                                                                                                                                                                                                                              
| trurl.c: In function ???get???:                                                                                                                                                                                                                                                
| trurl.c:874:13: error: assignment discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                       
|   874 |         end = strchr(ptr, endbyte);                                                                                                                                                                                                                                    
|       |             ^                                                                                                                                                                                                                                                          
| trurl.c:890:14: error: assignment discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                       
|   890 |           cl = memchr(ptr, ':', vlen);                                                                                                                                                                                                                                 
|       |              ^                                                                                                                                                                                                                                                         
| trurl.c: In function ???setone???:                                                                                                                                                                                                                                             
| trurl.c:1027:15: error: initialization discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                  
|  1027 |   char *ptr = strchr(setline, '=');                                                                                                                                                                                                                                    
|       |               ^~~~~~                                                                                                                                                                                                                                                   
| trurl.c: In function ???canonical_path???:                                                                                                                                                                                                                                     
| trurl.c:1697:8: error: assignment discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                       
|  1697 |     sl = memchr(path, '/', len);                                                                                                                                                                                                                                       
|       |        ^                                                                                                                                                                                                                                                               
| trurl.c: In function ???singleurl???:                                                                                                                                                                                                                                          
| trurl.c:1821:13: error: assignment discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                      
|  1821 |         sep = strchr(part, '=');                                                                                                                                                                                                                                       
|       |             ^                                                                                                                                                                                                                                                          
| trurl.c:1857:11: error: assignment discards ???const??? qualifier from pointer target type [-Werror=discarded-qualifiers]                                                                                                                                                      
|  1857 |       sep = strchr(w, ' ');                                                                                                                                                                                                                                            
|       |           ^                                                                                                                                                                                                                                                            
| cc1: all warnings being treated as errors                                                                                                                                                                                                                                      
| make[1]: *** [<builtin>: trurl.o] Error 1                                                                                                                                                                                                                                      
| make[1]: Leaving directory '/build/reproducible-path/trurl-0.16.1'                                                                                                                                                                                                             
| dh_auto_build: error: make -j128 INSTALL="install --strip-program=true" returned exit code 2                                                                                                                                                                                   
| make: *** [debian/rules:7: binary] Error 25                                                                                                                                                                                                                                    
| dpkg-buildpackage: error: debian/rules binary subprocess failed with exit status 2               
```                                                                                                                                                                              
                                                                                                                                                                                                                                                                                 
The full build log is available here:

https://people.debian.org/~ema/glibc-2.43-rebuilds/output-1/trurl_arm64.build                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                 
The issue is due to ISO C23 declaration of bsearch, memchr, strchr,                                                                                                                                                                                                              
strpbrk, strrchr, strstr, wcschr, wcspbrk, wcsrchr, wcsstr and wmemchr,                                                                                                                                                                                                          
which now returns a pointer to a const-qualified type when the input                                                                                                                                                                                                             
argument is a pointer to a const-qualified type [2].

**Comment by vszakats** [comment]
Thanks @abbbi, it should be fixed via #432.
